defultss = {
	"time_add": None,
	"group_name":None,
    "stats": {},
    "ban":True,
    "talk":True,
    "talk_kam":False,
    "talk_por":False,
    "ectar":True,
    "silent_ban":False,
    "silent_ectart":False,
    "num_ectart":3,
	"vip": {"vip":False, "time_start":None,"time_end":None},
	"spam_user":{},
	"list_filters":[],
    "num_ectar":3,
	"type_user": {
    	"manager": None,
    	"no_ansewr": {},
    	"mauf": {},
	    "admin": {},
	    "kill":{},
	    "silent": {}
    },
    "funny": {"funny":True, "mo":True, "sa":True, "ta":True, "ab":True, "tas":True, "fon_t":True, "sek":True,
            "day":True, "download_p":True, "download_s":True, "arz":True, "shan":True, "shas":True, "shog":True, "film":True, 
            "hiy":True, "ogh":True, "tavl":True, "pnp":True, "jok":True, "jok_kh":True, "alky":True, "bio":True, "dans":True,
            "dastan":True, "dialog":True, "sheer":True, "angiz":True, "chal":True, "hadis":True, "break":True, "love":True, 
            "aye":True, "tarf":True, "ghan":True, "sh_s":True, "sh_h":True, "sh_mvlv":True, "sh_mvla":True, "sh_ne":True,
            "sh_fr":True, "sh_sh":True, "man":True, "hosh":True, "vaz":True, "sang":True, "gifs":True, "fal":True, "riddles":True},
    "type_message":{
        "filters": {"delete": True,"ban": True, "ectar": True, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "text": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "hang_code": {"delete": True,"ban": True, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":0},
	    "spam": {"delete": True,"ban": True, "ectar": True, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "metadata": {"delete": True,"ban": True, "ectar": True, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "hash": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "gif": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "forwarded": {"delete": True,"ban": True, "ectar": True, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "link": {"delete": True,"ban": True, "ectar": True, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "id": {"delete": True,"ban": True, "ectar": True, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "photo": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "video": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "audio": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "voice": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "document": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "archive": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "executable": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "font": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "sticker": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "poll": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "contact": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "location": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3},
	    "live_location": {"delete": False,"ban": False, "ectar": False, "ban_silent":False,"ectar_silent":False,"num_ectar":3}
    },
    
    
    
	"num_message":{
		"all_message": 0,
	    "num_text": 0,
	    "num_photo": 0,
        "num_filters": 0,
	    "num_video": 0,
	    "num_voice": 0,
	    "num_link": 0,
	    "num_id": 0,
	    "num_contact": 0,
	    "num_location": 0,
	    "num_audio": 0,
	    "num_forwarded": 0,
	    "num_live_location": 0,
	    "num_poll": 0,
	    "num_sticker": 0,
	    "num_font": 0,
	    "num_executable": 0,
	    "num_archive": 0,
	    "num_document": 0
	},
	"user_ectar":{},
    "users": {}
}